### ISSUE TITLE
Tournament bracket

### ISSUE THREAD

**Issue by vitalrum** [PKPK-Carnage/OTGanttChartKit#1]
Hello guys, thank for good work.
Tell me please, can you create something like this:
![123temp](https://user-images.githubusercontent.com/5136852/29959936-4c50e8aa-8f02-11e7-8de0-b6f6d8c34608.jpg)

Tournament bracket with scroll, animations, update with socket, database and good performance for tournament with million peoples ?

**Comment by Frog-Frog** [comment]
I'll give it a try in my free time. But please don't get your hopes up...

**Comment by Frog-Frog** [comment]
I made a new repository.
https://github.com/PKPK-Carnage/OTTournamentView

I plan to develop it in this repository.
If there is progress, I will commit.
Please check this out.

**Comment by vitalrum** [comment]
thank you
